import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  //introSidebar: [{type: 'autogenerated', dirName: 'intro'}],
  guideSidebar: [{type: 'autogenerated', dirName: 'guide'}],
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial'}],
};

export default sidebars;
